/* eslint-disable */
// Auto-generated by @skalfa/skalfa-cli. Do not edit manually.

export * from "./types";
export * from "./manifest";
export { default as id } from "./locales/id";
export { default as en } from "./locales/en";

