/* eslint-disable */
// This file was auto-generated by @skalfa/skalfa-cli. Do not edit manually.

export interface Lang {
  base: {
    appName(): string;
    welcomeTitle(): string;
    welcomeSubtitle(): string;
    save(): string;
    cancel(): string;
    delete(): string;
    add(): string;
    edit(): string;
    detail(): string;
    print(): string;
    import(): string;
    export(): string;
    apply(): string;
    clear(): string;
    confirm(): string;
    addTitle(): string;
    editTitle(): string;
    detailTitle(): string;
    importTitle(): string;
    exportTitle(): string;
    deleteTitle(params: { data: string | number }): string;
    success(): string;
    failed(): string;
    inputPlaceholder(params: { field: string | number }): string;
    formConfirm(): string;
    formFailed(): string;
    confirmFailed(): string;
    shortcut(): string;
    shortcutList(): string;
    shortcutDown(): string;
    shortcutUp(): string;
    shortcutDelete(): string;
    shortcutEdit(): string;
    shortcutDetail(): string;
    shortcutBack(): string;
    shortcutSearch(): string;
    shortcutFilter(): string;
    shortcutSort(): string;
    shortcutRefresh(): string;
    searchPlaceholder(): string;
    selectable(): string;
    sort(): string;
    filter(): string;
    filterLogic(): string;
    filterOperator(): string;
    filterFrom(): string;
    filterTo(): string;
    filterBookmark(): string;
    filterBookmarkEmpty(): string;
    filterBookmarkPlaceholder(): string;
    filterBookmarkNew(): string;
    filterBookmarkNewPlaceholder(): string;
    column(): string;
    tableLoading(): string;
    tableEmpty(): string;
    tableSelected(): string;
  };
  validation: {
    required(): string;
    min(params: { min: string | number }): string;
    max(params: { max: string | number }): string;
    min_max(params: { min: string | number; max: string | number }): string;
    phone(): string;
    url(): string;
    uppercase(): string;
    lowercase(): string;
    numeric(): string;
    email(): string;
    in(params: { keywords: string | number }): string;
    not_in(params: { keywords: string | number }): string;
    regex(): string;
    invalid_file_type(params: { extension: string | number }): string;
    max_file_size(params: { maxFileSize: string | number }): string;
  };
}

export interface ModuleLangs {
}

declare module "@skalfa/skalfa-lang" {
  export function useLang(): Lang;
  export function useLang<K extends keyof ModuleLangs>(moduleName: K): Lang & ModuleLangs[K];
}
