// Auto-generated by scripts/generate.ts — DO NOT EDIT
import type { SVGProps } from "react";
import { iconRegistry, type IconName } from "./registry";

export interface IconProps extends SVGProps<SVGSVGElement> {
  /** Name of the icon (kebab-case, e.g. "chevron-left") */
  icon: IconName;
  className?: string;
  onClick?: any;
}

export function Icon({ icon, style, ...props }: IconProps) {
  const SvgComponent = iconRegistry[icon];

  if (!SvgComponent) {
    if (typeof window !== "undefined") {
      console.warn(`[skalfa-icon] Icon "${icon}" not found in registry`);
    }
    return null;
  }

  return (
    <SvgComponent
      width="1em"
      height="1em"
      style={{
        display: "inline-block",
        verticalAlign: "-0.125em",
        ...style,
      }}
      {...props}
    />
  );
}
