// Auto-generated by scripts/generate.ts — DO NOT EDIT
export { Icon } from "./Icon";
export type { IconProps } from "./Icon";
export { iconRegistry } from "./registry";
export type { IconName, IconComponent } from "./registry";
export * from "./icons";
